#!/bin/bash

hash() {
  local seed="${1}"
  local hash="$(
      tr -d '[:space:]' <<<"${seed}" | \
      openssl md5 -binary | \
      base64 | \
      tr -d -c '[:alnum:]')"
  echo "${hash:0:8}"
}

while :; do
  read -sp 'Master password: ' password
  echo
  read -p "Password hash is $(hash "${password}"). Right? [Y/n] " yesno
  case "${yesno}" in
    [Nn]*) continue;;
    *) break;;
  esac
done

read -p 'Domain: ' domain
domain="$(echo "${domain}" | tr '[A-Z]' '[a-z]')"
seed="${password}@${domain}"

password="$(hash ${seed})"
if [ "${SSH_TTY+set}" == '' ]; then
  if which pbcopy >/dev/null 2>/dev/null; then
    echo -n "${password}" | pbcopy
    echo 'Password was copied to your clipboard.'
    exit 0
  fi
fi

echo "${password}"
